baseURL = 'https://metodika21cm.netlify.app'
languageCode = 'ru'
enableInlineShortcodes = true
title = 'Методика 21 см'
theme = 'pehtheme'
ignoreErrors = ["error-remote-getjson"]

paginate = '9' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Методика безоперационного увеличения полового члена в домашних условиях. Методика 21 см'
	mainSections = 'posts'

[author]
	name = 'Marcus'
	bio = 'Создатель и разработчик данной методики. Telegram для связи ⬇'
	avatar = '/images/ava.png'

  

[menu] # Menu management
	[[menu.main]]
		name = 'Главная'
		pageRef = '/'
		weight = 5
	[[menu.main]]
		name = 'Инфо'
		pageRef = '/abouts'
		weight = 10
		exclude = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'