[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.123.8"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"


[[redirects]]
  from = "http://metodika21cm.space/:splat"
  to = "https://metodika21cm.space/:splat"
  status = 301
  force = true